# Basic
title: Xiang
description: 学习笔记

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# The blog button should not be removed.
blog_button:
    title: Blog

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

comment:
    disqus: xiang-1

